name: platform_device_id
description: You can get device id from platform - linux/mac/windows/android/ios/web.
version: 1.0.1
homepage: https://github.com/BestBurning/platform_device_id

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^10.1.2
  android_id: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


